export default {
	SET_SITE_OPTION: 'SET_SITE_OPTION',
	SET_POSTS: 'SET_POSTS',
	SET_POST_TYPES: 'SET_POST_TYPES',
	SET_TAXONOMIES: 'SET_TAXONOMIES',
	SET_QUERIED_OBJECT: 'SET_QUERIED_OBJECT',
	SET_HASMORE: 'SET_HASMORE'
}
